version: '3.8'

volumes:
  database: {}
  pgadmin-data: {}

services:
  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: device
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
    ports:
      - '5432:5432'
    volumes:
      - 'database:/var/lib/postgresql@14/data:rw'

  php:
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/device-referential
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/device-referential
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@device.localhost
      PGADMIN_DEFAULT_PASSWORD: equipe
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database
