controllers:
    resource: ../src/Infrastructure/Controller/
    type: attribute
    prefix: '/{_locale}'
    trailing_slash_on_root: false
    requirements:
        _locale: en|fr

app_default:
    path: /
    controller: App\Infrastructure\Controller\DefaultController
    methods: GET

app_logout:
    path: /logout
    methods: GET
