name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      postgresql:
        image: postgres:15.3-alpine
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: device
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v1

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Init CI environment variables
        # HACK: Symfony won't read from 'env: { DATABASE_URL: ... }', so we need to edit
        # .env directly.
        run: |
          echo "DATABASE_URL=postgresql://app:app@localhost:5432/device" >> .env

      - name: CI
        run: make ci BIN_PHP="php" NPM="npm" BIN_CONSOLE="php bin/console" BIN_COMPOSER="composer"

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
